config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  namespace :api do
    resources :artists do
      resources :songs
      delete '/songs', to: 'songs#destroy_all'
    end
  end

  resources :artists do
    resources :songs
    resources :photos
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs, dependent: :destroy
  has_many :photos, dependent: :destroy
  accepts_nested_attributes_for :songs, allow_destroy: true

  validates :name, presence: true
  validates :genre, presence: true
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :artist

  mount_uploader :image, ImageUploader
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist, inverse_of: :songs
  validates_presence_of :artist

  validates :name, presence: true
end

app/controllers/api/songs_controller.rb
class Api::SongsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    render status: 200, json: {
      songs: Song.all
    }.to_json
  end

  def create
    artist = Artist.find(params[:artist_id])
    song = artist.songs.new(song_params)

    if song.save
      render status: 200, json: {
        song: song,
      }.to_json
    else
      render status: 422, json: {
        errors: song.errors
      }.to_json
    end
  end

  def destroy
    song = Song.find(params[:id])

    if song.destroy
      render status: 200, json: {
        song: song
      }.to_json
    else
      render status: 422, json: {
        errors: song.errors
      }.to_json
    end
  end

  def destroy_all
    artist = Artist.find(params[:artist_id])
    songs = artist.songs
    songs.destroy_all

    render status: 200, json: {
      message: "All songs deleted :("
    }.to_json
  end

  private

  def song_params
    params.permit(:name, :artist_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.all
  end

  def show
    @artist = Artist.find(params[:id])
    @photos = @artist.photos
    @songs = @artist.songs
  end

  def new
    @artist = Artist.new
  end

  def edit
    @artist = Artist.find(params[:id])
    @photos = @artist.photos
    @songs = @artist.songs
  end

  def create
    @artist = Artist.new(artist_params)

    if @artist.save
      image_params.each do |image|
        @artist.photos.create(image: image)
      end

      redirect_to @artist, notice: "Artist created"
    else
      render :new
    end
  end

  def update
    @artist = Artist.find(params[:id])
    if @artist.update(artist_params)
      image_params.each do |image|
        @artist.photos.create(image: image)
      end

      redirect_to @artist, notice: "Artist updated!"
    else
      render :edit
    end
  end

  def destroy
    artist = Artist.find(params[:id])
    artist.destroy

    redirect_to artists_path
  end

  private

  def set_artist
    @artist = Artist.find(params[:id])
  end

  def artist_params
    params.require(:artist).permit(
      :name, :bio, :genre,
      songs_attributes: [:name]
    )
  end

  def image_params
    params[:images].present? ? params.require(:images) : []
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @artists = Artist.all
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def destroy
    photo = Photo.find(params[:id])
    @artist = photo.artist
    photo.destroy

    redirect_to edit_artist_path(@artist), notice: "Photo removed"
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  def new
    @song = Song.new
    @artist = Artist.find(params[:artist_id])
  end

  def create
    @artist = Artist.find(params[:artist_id])
    @song = @artist.songs.new(song_params)

    if @song.save
      redirect_to @artist, notice: "Song added"
    else
      render :new
    end
  end

  def destroy
    song = Song.find(params[:id])
    @artist = song.artist
    song.destroy

    redirect_to artist_path(@artist), notice: "Song removed"
  end

  private

  def song_params
    params.require(:song).permit(:name, :artist_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_form.html.erb
<%= form_for @artist, html: { multipart: true } do |f| %>
  <% if @artist.errors.any? %>
    <ul><% @artist.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <div class="form-row">
    <label>
      <span><%= f.label :name %></span>
      <%= f.text_field :name, class: "input" %>
  </div>
  <div class="form-row">
    <label>
      <span><%= f.label :genre %></span>
      <%= f.text_field :genre, class: "input" %>
  </div>
  <div class="form-row">
    <label>
      <span><%= f.label :bio %></span>
      <%= f.text_field :bio, class: "textarea" %>
  </div>
  <div class="form-row">
    <%= f.submit class: "submit-button" %>
  </div>

  <div class="form-row">
      <div class="uploader">
        Upload Photos
        <%= file_field_tag "images[]", class: "btn btn-default", type: :file, multiple: true %>
      </div>
  </div>

  <div id="photos">
    <%= render 'photos/list' %>
  </div>
  <% end %>

app/views/artists/edit.html.erb
<div class="show-pages">
  <div class="container">
    <div class="form-basic">
      <div class="form-title-row">
        <h1>Edit artist</h1>
      </div>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/artists/index.html.erb
<div class="show-pages">
  <div class="artists-index">
    <% @artists.each do |artist| %>
      <div class="artist">
        <div class="artist-photo">
          <% if !artist.photos.first.nil? %>
            <%= image_tag artist.photos.first.image.list_item %>
          <% end %>
        </div>
        <div class="artist-details">
          <p class="artist-name"><%= artist.name %></p>
          <p class="genre"><%= artist.genre %></p>
          <div class="artist-actions">
            <%= link_to 'Show', artist %>
            <%= link_to 'Edit', edit_artist_path(artist) %>
            <%= link_to 'Delete', artist, method: :delete, data: { confirm: "Are you sure you want to delete this artist?" } %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/artists/new.html.erb
<div class="show-pages">
  <div class="container">
    <div class="form-basic">
      <div class="form-title-row">
        <h1>Create new artist</h1>
      </div>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/artists/show.html.erb
<div class="show-pages">
  <div class="container">
    <div class="artist-photos">
      <% @artist.photos.each do |photo| %>
        <div class="artist-photo">
          <%= image_tag photo.image.thumbnail %>
        </div>
      <% end %>
    </div>

    <div class="artist-info">
      <div class="artist-buttons">
        <%= link_to 'Edit artist', edit_artist_path, class: "btn btn-primary" %>
        <%= link_to 'Delete artist', artist_path(@artist), class: "btn btn-danger", method: :delete, data: { confirm: "Are you sure you want to delete this artist?" } %>
      </div>

      <h1><%= @artist.name %></h1>

      <span class="artist-genre">Genre: <%= @artist.genre %></span>

      <% if @artist.bio.present? %>
        <h2>Biography</h2>
        <p><%= @artist.bio %></p>
      <% end %>

      <div class="songs">
        <%= render 'songs/list' %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codaisseurify</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'https://fonts.googleapis.com/css?family=Nunito:200i,400,700' %>
    <%= stylesheet_link_tag    'application', media: 'all' %>


  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
  <div id="homepage">
    <div class="home-header">
      <h1>Codaisseurify</h1>
      <h3> We &#10084; music </h3>
      <%= link_to 'Browse artists', artists_path %>
      <%= link_to 'Add artists', new_artist_path %>
    </div>
  </div>

app/views/photos/_list.html.erb
<% if @photos %>
  <% @photos.each do |photo| %>
    <div class="panel panel-default">
      <div class="panel-heading preview">
        <%= image_tag photo.image.thumbnail %>
      </div>
      <div class="panel-body">
        <%= link_to "Delete", artist_photo_path(@artist.id, photo.id), class: "btn btn-default", method: :delete, data: { confirm: "Are you sure you want to delete this photo?" } %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Codaisseurify", root_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "All Artists", artists_path %></li>
          <li><%= link_to 'New artist', new_artist_path %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/songs/_form.html.erb
<form onSubmit="submitSong(event)">
  <label for="song-input">Add a new song</label>
  <input type="text" id="song-input">
</form>

app/views/songs/_list.html.erb
<h3>Songs:</h3>
<p id="empty-list">This artist has no songs yet.</p>
<%= render 'songs/form' %>

<ul id="songs-list">
  <% if @songs.present? %>
    <% @songs.each do |song| %>
      <li data-id="<%= song.id %>"><%= song.name %><button class="delete-button">x</button></li>
    <% end %>
  <% end %>
</ul>

<button type="button" id="delete-all">Delete all songs</button>

<script>
  var artistId = <%= @artist.id %>;
</script>